query Category($id: ID!) {
  category(id: $id) {
    data {
      id
      attributes {
        name
        articles {
          data {
            id
            attributes {
              title
              content
              image {
                data {
                  attributes {
                    url
                  }
                }
              }
              category {
                data {
                  attributes {
                    name
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
